// react_backup/Signup.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Ticket, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { useAuthStore } from '../stores/auth';
import DecorativeCircles from '../components/DecorativeCircles';
import { Card } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';

export default function Signup() {
  const navigate = useNavigate();
  const signup = useAuthStore((state) => state.signup);

  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [nameError, setNameError] = useState('');
  const [emailError, setEmailError] = useState('');
  const [passwordError, setPasswordError] = useState('');
  const [confirmPasswordError, setConfirmPasswordError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setNameError('');
    setEmailError('');
    setPasswordError('');
    setConfirmPasswordError('');

    // Client-side validation
    let hasError = false;

    if (!name) {
      setNameError('Name is required');
      hasError = true;
    }

    if (!email) {
      setEmailError('Email is required');
      hasError = true;
    }

    if (!password) {
      setPasswordError('Password is required');
      hasError = true;
    }

    if (password !== confirmPassword) {
      setConfirmPasswordError('Passwords do not match');
      hasError = true;
    }

    if (hasError) return;

    setIsLoading(true);
    const result = await signup(name, email, password);
    setIsLoading(false);

    if (result.success) {
      toast.success('Account created successfully!');
      navigate('/dashboard');
    } else {
      if (result.error?.toLowerCase().includes('email')) {
        setEmailError(result.error);
      } else if (result.error?.toLowerCase().includes('password')) {
        setPasswordError(result.error);
      } else {
        toast.error(result.error || 'Signup failed');
      }
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 relative overflow-hidden py-12">
      <DecorativeCircles />

      <div className="w-full max-w-md px-4 relative z-10">
        <div className="text-center mb-8">
          <Link to="/" className="inline-flex items-center gap-2 mb-6">
            <div className="w-12 h-12 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-lg flex items-center justify-center">
              <Ticket className="w-7 h-7 text-white" />
            </div>
            <span className="font-semibold text-gray-900">TicketFlow</span>
          </Link>
        </div>

        <Card className="p-8 shadow-xl">
          <h1 className="text-gray-900 mb-2 text-center">Create Account</h1>
          <p className="text-gray-600 text-center mb-6">Get started with TicketFlow today</p>

          <form onSubmit={handleSubmit} className="space-y-5">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input
                id="name"
                type="text"
                placeholder="John Doe"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className={nameError ? 'border-red-500' : ''}
                disabled={isLoading}
              />
              {nameError && <p className="text-red-600">{nameError}</p>}
            </div>

            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="your@email.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className={emailError ? 'border-red-500' : ''}
                disabled={isLoading}
              />
              {emailError && <p className="text-red-600">{emailError}</p>}
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className={passwordError ? 'border-red-500' : ''}
                disabled={isLoading}
              />
              {passwordError && <p className="text-red-600">{passwordError}</p>}
            </div>

            <div className="space-y-2">
              <Label htmlFor="confirmPassword">Confirm Password</Label>
              <Input
                id="confirmPassword"
                type="password"
                placeholder="••••••••"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                className={confirmPasswordError ? 'border-red-500' : ''}
                disabled={isLoading}
              />
              {confirmPasswordError && <p className="text-red-600">{confirmPasswordError}</p>}
            </div>

            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Creating account...
                </>
              ) : (
                'Sign Up'
              )}
            </Button>
          </form>

          <div className="mt-6 text-center">
            <p className="text-gray-600">
              Already have an account?{' '}
              <Link to="/login" className="text-indigo-600 hover:text-indigo-700">
                Login
              </Link>
            </p>
          </div>
        </Card>
      </div>
    </div>
  );
}

// src/pages/Signup.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 relative overflow-hidden py-12 dark:bg-none dark:bg-card dark:text-foreground">
    <DecorativeCircles />

    <div class="w-full max-w-md px-4 relative z-10">
      <div class="text-center mb-8">
        <router-link to="/" class="inline-flex items-center gap-2 mb-6">
          <div class="w-12 h-12 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-lg flex items-center justify-center">
            <Ticket class="w-7 h-7 text-white" />
          </div>
          <span class="font-semibold text-foreground">TicketFlow</span>
        </router-link>
      </div>

      <VCard class="p-8 shadow-xl">
  <h1 class="text-foreground mb-2 text-center">Create Account</h1>
  <p class="text-muted text-center mb-6">Get started with TicketFlow today</p>

        <form @submit.prevent="handleSubmit" class="space-y-5">
          <div class="space-y-2">
            <VLabel for="name">Name</VLabel>
            <VInput
              id="name"
              type="text"
              placeholder="John Doe"
              v-model="name"
              :class="nameError ? 'border-red-500' : ''"
              :disabled="isLoading"
            />
            <p v-if="nameError" class="text-red-600">{{ nameError }}</p>
          </div>

          <div class="space-y-2">
            <VLabel for="email">Email</VLabel>
            <VInput
              id="email"
              type="email"
              placeholder="your@email.com"
              v-model="email"
              :class="emailError ? 'border-red-500' : ''"
              :disabled="isLoading"
            />
            <p v-if="emailError" class="text-red-600">{{ emailError }}</p>
          </div>

          <div class="space-y-2">
            <VLabel for="password">Password</VLabel>
            <VInput
              id="password"
              type="password"
              placeholder="••••••••"
              v-model="password"
              :class="passwordError ? 'border-red-500' : ''"
              :disabled="isLoading"
            />
            <p v-if="passwordError" class="text-red-600">{{ passwordError }}</p>
          </div>

          <div class="space-y-2">
            <VLabel for="confirmPassword">Confirm Password</VLabel>
            <VInput
              id="confirmPassword"
              type="password"
              placeholder="••••••••"
              v-model="confirmPassword"
              :class="confirmPasswordError ? 'border-red-500' : ''"
              :disabled="isLoading"
            />
            <p v-if="confirmPasswordError" class="text-red-600">{{ confirmPasswordError }}</p>
          </div>

          <VButton type="submit" class="w-full" :disabled="isLoading">
            <template v-if="isLoading">
              <Loader2 class="mr-2 h-4 w-4 animate-spin" />
              Creating account...
            </template>
            <template v-else>
              Sign Up
            </template>
          </VButton>
        </form>

        <div class="mt-6 text-center">
          <p class="text-muted">
            Already have an account?
            <router-link to="/login" class="text-indigo-600 hover:text-indigo-700">
              Login
            </router-link>
          </p>
        </div>
      </VCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { toast } from 'sonner'
import DecorativeCircles from '../components/DecorativeCircles.vue'
import VCard from '../components/ui/VCard.vue'
import VButton from '../components/ui/VButton.vue'
import VInput from '../components/ui/VInput.vue'
import VLabel from '../components/ui/VLabel.vue'
import { Ticket, Loader2 } from 'lucide-vue-next'

const router = useRouter()
const authStore = useAuthStore()

const name = ref('')
const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const nameError = ref('')
const emailError = ref('')
const passwordError = ref('')
const confirmPasswordError = ref('')
const isLoading = ref(false)

const handleSubmit = async () => {
  nameError.value = ''
  emailError.value = ''
  passwordError.value = ''
  confirmPasswordError.value = ''

  // Client-side validation
  let hasError = false

  if (!name.value) {
    nameError.value = 'Name is required'
    hasError = true
  }

  if (!email.value) {
    emailError.value = 'Email is required'
    hasError = true
  }

  if (!password.value) {
    passwordError.value = 'Password is required'
    hasError = true
  }

  if (password.value !== confirmPassword.value) {
    confirmPasswordError.value = 'Passwords do not match'
    hasError = true
  }

  if (hasError) return

  isLoading.value = true
  const result = await authStore.signup(name.value, email.value, password.value)
  isLoading.value = false

  if (result.success) {
    toast.success('Account created successfully!')
    router.push('/dashboard')
  } else {
    if (result.error?.toLowerCase().includes('email')) {
      emailError.value = result.error
    } else if (result.error?.toLowerCase().includes('password')) {
      passwordError.value = result.error
    } else {
      toast.error(result.error || 'Signup failed')
    }
  }
}
</script>
